trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: DevPlan
    displayName: Dev Plan
    jobs:
      - job:
        displayName: Terraform Plan - Dev Environment
        variables:
          - template: vars/dev_vars.yml
        steps:
          - template: templates/terraform_plan.yml
            parameters:
              serviceConnectionName: devops
              backendAzureRmResourceGroupName: $(rgName)
              backendAzureRmStorageAccountName: $(storageAccountName)
              backendAzureRmContainerName: $(backendAzureRmContainerName)
              backendAzureRmKey: $(tfState)
              tfComponent: $(tfComponent)
              tfExecutionDir: $(tfExecutionDir)
              tfVarFileName: $(tfVarFileName)
  - stage: DevApply
    displayName: Dev Apply
    jobs:
      - deployment: Deploy
        displayName: Terraform Apply - Dev Environment
        pool:
          vmImage: 'ubuntu-latest'
        environment: dev
        variables:
          - template: vars/dev_vars.yml
        strategy:
          runOnce:
            deploy:
              steps:
                - template: templates/terraform_apply.yml
                  parameters:
                    serviceConnectionName: devops
                    backendAzureRmResourceGroupName: $(rgName)
                    backendAzureRmStorageAccountName: $(storageAccountName)
                    backendAzureRmContainerName: $(backendAzureRmContainerName)
                    backendAzureRmKey: $(tfState)
                    tfComponent: $(tfComponent)
                    tfExecutionDir: $(tfExecutionDir)
                    tfVarFileName: $(tfVarFileName)
  - stage: StagingPlan
      displayName: Staging Plan
      jobs:
        - job:
          displayName: Terraform Plan - Staging Environment
          variables:
            - template: vars/staging_vars.yml
          steps:
            - template: templates/terraform_plan.yml
              parameters:
                serviceConnectionName: devops
                backendAzureRmResourceGroupName: $(rgName)
                backendAzureRmStorageAccountName: $(storageAccountName)
                backendAzureRmContainerName: $(backendAzureRmContainerName)
                backendAzureRmKey: $(tfState)
                tfComponent: $(tfComponent)
                tfExecutionDir: $(tfExecutionDir)
                tfVarFileName: $(tfVarFileName)
    - stage: StagingApply
      displayName: Staging Apply
      jobs:
        - deployment: Deploy
          displayName: Terraform Apply - Staging Environment
          pool:
            vmImage: 'ubuntu-latest'
          environment: staging
          variables:
            - template: vars/staging_vars.yml
          strategy:
            runOnce:
              deploy:
                steps:
                  - template: templates/terraform_apply.yml
                    parameters:
                      serviceConnectionName: devops
                      backendAzureRmResourceGroupName: $(rgName)
                      backendAzureRmStorageAccountName: $(storageAccountName)
                      backendAzureRmContainerName: $(backendAzureRmContainerName)
                      backendAzureRmKey: $(tfState)
                      tfComponent: $(tfComponent)
                      tfExecutionDir: $(tfExecutionDir)
                      tfVarFileName: $(tfVarFileName)
